# This is a config for E2B sandbox template.
# You can use template ID (3nibi06u6zvaqzzvu98y) or template name (vibe-next-dev-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-next-dev-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-next-dev-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-next-dev-2')

team_id = "965c1ded-af29-4f12-ba08-4070f2aa0ad5"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-next-dev-2"
template_id = "3nibi06u6zvaqzzvu98y"
